services:
  postgres:
    image: postgres:latest
    env_file: ".env"
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - db_network

  redis:
    image: redis:latest
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    restart: unless-stopped
    volumes:
      - ./redisdata:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - cache_network

  app:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --workers 4"
    env_file: ".env"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    networks:
      - db_network
      - cache_network

networks:
  db_network:
    driver: bridge
  cache_network:
    driver: bridge
